=== DigiGradProject/SmartBankSearch/nbe-ai-search-mvp/data/schemas/document.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "NBE Document",
  "type": "object",
  "required": ["id", "title", "url", "language", "content"],
  "properties": {
    "id": { "type": "string" },
    "title": { "type": "string" },
    "url": { "type": "string", "format": "uri" },
    "language": { "enum": ["ar", "en"] },
    "content": { "type": "string", "minLength": 1 },
    "metadata": { "type": "object" }
  }
}

=== DigiGradProject/SmartBankSearch/output/f4e5896a28b9a519.json
{
  "id": "f4e5896a28b9a519",
  "title": "البنك الأهلى المصري",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22CreditCardsID%22%2C%22ProductID%22%3A%22%D9%81%D9%8A%D8%B2%D8%A7%20%D8%A7%D9%86%D9%81%D9%8A%D9%86%D9%8A%D8%AA_18703%22%7Dhttps://www.nbe.com.eg/NBE/E/#/AR/ProductCategory?inParams=%7B%22CategoryID%22%3A%22DepitCardsID%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nCatagory landing div\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "a89cf1c564089db238fd0bf958e0654d148a2d8f4eba52a506c5ffe0ed97c797",
    "extracted_at": "2026-07-14T08:40:30.205757+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/1eafd131a5e27f1f.json
{
  "id": "1eafd131a5e27f1f",
  "title": "البنك الأهلى المصرى - الحسابات",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductCategory?inParams=%7B%22CategoryID%22%3A%22AccountsID%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالحسابات\n\nCatagory landing div\n\nالحسابات الجارية\n\nإمكانية القيام بكافة المعاملات المصرفية اليومية في منتهي السهولة الآن مع الحساب الجاري من البنك الأهلي المصري.\n\nحسابات التوفير\n\nاستمتع بالحصول علي عائد مميز علي مدخراتك بدورية العائد التي تناسبك\n\nمبادرة افتح حسابك في مصر\n\n#CategoryMiddleContainer#\n\n#ProductShortLayoutContainer#\n\nاظغط للمقارنة بين المنتجات.\n\nشروط و احكام الحسابات النشطة والراكدة في ضوء التعليمات الصادرة عن البنك المركزي المصري\n\nتنويه هام:\n\nيرجي التوجه الي اقرب فرع لتحديث بياناتكم وذلك حرصاً على استمرار تقديم خدماتنا بسهوله ويسر .\n\nمدرج كافة عناوين الفروع على الرابط التالي:\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "6ab6f3126879d568a47387406fe5b58eb99ff16b147aa5ce03d4e7bc6e5260bd",
    "extracted_at": "2026-07-14T08:39:30.365006+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/13c71f9b63ac85cf.json
{
  "id": "13c71f9b63ac85cf",
  "title": "البنك الأهلى المصرى - الحسابات الجارية",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductCategory?inParams=%7B%22CategoryID%22%3A%22CurrentAccountsID%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالحسابات\n\nالحسابات الجارية\n\nCatagory landing div\n\n#CategoryShortLayoutContainer#\n\n#CategoryMiddleContainer#\n\nالحساب الجاري\n\n2500\n\nجم\n\nمن لهم حق فتح الحساب\n\nمصري\n\nأجنبي\n\nحساب فايدة بلس\n\n10,000\n\n50,000\n\nحساب الأهلي اليومي\n\n500,000\n\nاظغط للمقارنة بين المنتجات.\n\n#CategoryFooterContainer#\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "8e1fcbca304accf0018949e7fb516c25457946c9184a8daf739bb266828b607f",
    "extracted_at": "2026-07-14T08:39:32.648726+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/190e1a66d7f08a8b.json
{
  "id": "190e1a66d7f08a8b",
  "title": "البنك الأهلى المصرى - الحساب الجاري",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22CurrentAccountsID%22%2C%22ProductID%22%3A%22%D8%A7%D9%84%D8%AD%D8%B3%D8%A7%D8%A8%20%D8%A7%D9%84%D8%AC%D8%A7%D8%B1%D9%8A_6202%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالحسابات\n\nالحسابات الجارية\n\nالحساب الجاري\n\nالحد الأدنى لفتح الحساب\n\n2500\n\nجم\n\n100\n\nدولار أمريكي\n\nمن لهم حق فتح الحساب\n\nالمميزات\n\nالاوراق المطلوبة و مميزات أخرى\n\nنسخة من بطاقة الهوية / جواز السفر\n\nتمتع بالإعفاء من مصاريف فتح الحساب والحد الأدنى لفتح الحساب عند فتح حسابك من خلال الأهلي نت/الأهلي موبايل.\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "d6c49fd4911df70a8caf80c1aeb405c48178770f953d1ed93847c72814a2fa13",
    "extracted_at": "2026-07-14T08:39:34.060855+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/4c839f7433e64bf1.json
{
  "id": "4c839f7433e64bf1",
  "title": "البنك الأهلى المصرى - فيزا بلاتينم بالدولار الأمريكي",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22DepitCardsID%22%2C%22ProductID%22%3A%22%D9%81%D9%8A%D8%B2%D8%A7%20%D8%A8%D9%84%D8%A7%D8%AA%D9%8A%D9%86%D9%85%20%D8%A8%D8%A7%D9%84%D8%AF%D9%88%D9%84%D8%A7%D8%B1%20%D8%A7%D9%84%D8%A3%D9%85%D8%B1%D9%8A%D9%83%D9%8A_18811%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالبطاقات\n\nبطاقات الخصم المباشر\n\nفيزا بلاتينم بالدولار الأمريكي\n\n#ProductHeaderContainer#\n\nمميزات البطاقة\n\n5 سنوات\n\nدوليا\n\nمتاح\n\nالبطاقة مصممة لعملاء البنك من الأفراد الطبيعيين، أصحاب الحسابات بعملة الدولار الأمريكي.\n\nإمكانية استخدام البطاقة بالعملة الأجنبية في المشتريات لدى شبكة واسعة من التجار، والتسوق عبر الإنترنت، والسحب النقدي من ماكينات الصراف الآلي دوليًا فقط.\n\nإمكانية استخدام البطاقة من خلال ماكينات الصراف الآلي التابعة للبنك وذلك في الخدمات التالية: (تنشيط البطاقة - إنشاء رقم سري للبطاقة - الاستعلام عن رصيد الحسابات المربوطة بالبطاقة «دون إتاحة خدمة طباعة إيصال» - التحويل بين الحسابات المربوطة بالبطاقة).\n\nالإدراج التلقائي ببرنامج  Al Ahly Points الذي يتيح لكم الحصول على (20نقطة) مع كل دولار أمريكي يتم استخدامه في المشتريات.\n\nاستبدل نقاطك من خلال:\n\nاحتواء البطاقة على الخاصية اللاتلامسية الــ Contactless تتيح لكم تسوق سهل وآمن من خلال تمرير البطاقة فقط، والحد الأقصى لمبلغ العملية الواحدة التي تتم بدون إدخال الرقم السري هو (100 دولار أمريكي) أو (ما يعادله بالعملات الأجنبية) (قابلة للتعديل وفقًا لتعليمات البنك المركزي المصري).\n\nمركز اتصال مخصص لمساعدتك 24 ساعة يوميا (19523).\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nOthers Products\n\n#ProductOtherLayoutContainer#\n\nTo compare between products press...\n\n#ProductTypeFooterContainer#\n\nمميزات \nبطاقات الخصم المباشر\n\nالمرونة\n\nاستخدام البطاقة دوليا في المشتريات والسحب النقدى.\n\nالامان\n\nالتسوق الامن عبر الأنترنت من خلال خدمة الكود الامن للشراء (OTP)\n\n24/7 الأهلي فون\n\nنتشرف بخدمتكم واجابة جميع استفساراتكم من خلال خدمة\nالأهلي فون 19523 محليا و 0020225941200 دوليا\n\n#CategoryFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "ecd875925cd9b64c9d7f960ab91da0585cb3c9f27aaffafd98a51e2b8f520d29",
    "extracted_at": "2026-07-14T08:40:31.213345+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/a390284a2e964355.json
{
  "id": "a390284a2e964355",
  "title": "البنك الأهلى المصرى - خدمة الـ sweeping",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22287%22%2C%22ProductID%22%3A%22%D8%AE%D8%AF%D9%85%D8%A9%20%D8%A7%D9%84%D9%80%20sweeping_18773%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nخدمات الحسابات\n\nخدمة الـ sweeping\n\n#ProductHeaderContainer#\n\nخدمة الـتغطية التلقائية للحسابات Sweeping\n\nتقدم لك هذه الخدمة ميزة التغطية التلقائية لالتزاماتك المالية؛ ففي حال عدم كفاية الرصيد في حساب الخصم الخاص بك، يقوم النظام تلقائيًا بتحويل المبلغ المطلوب من حساباتك الأخرى بالعملة المحلية داخل البنك الأهلي المصري لتغطية هذا الالتزام فورًا.\n\nمحددات تطبيق الخدمة:\n\nالخدمة مفعّلة تلقائيًا لجميع العملاء الأفراد (الحاليين والجدد) الذين يمتلكون أكثر من حساب لدى البنك، دون الحاجة لتقديم طلب اشتراك.\n\nالخدمة مجانية.\n\nيتم تفعيل خدمة sweeping عند المطالبة بالالتزامات فقط.\n\nهذه الميزة مصممة لحمايتك وضمان استمرار معاملاتك بسلاسة، لذا فهي مفعّلة بشكل دائم وغير قابلة للإلغاء أو الإيقاف.\n\nالالتزامات التي تغطيها الخدمة (حاليًا):\n\nمستحقات بطاقتك الائتمانية.\n\nأقساط وأعباء مديونيات القروض.\n\nالشيكات المسحوبة على حسابك لدينا.\n\nالكمبيالات.\n\nالمصاريف السنوية للخزائن المؤجرة.\n\nمصاريف كشف الحسابات الدورية، والمصاريف الإدارية للحسابات.\n\nمصاريف تجديد بطاقات الخصم المباشر.\n\nخدمة التحويلات الصادرة بالعملة المحلية (ACH).\n\nحرصًا على تقديم أفضل تجربة مصرفية لك، قد نقوم مستقبلًا بإضافة التزامات جديدة لتغطيتها أو تعديل بعضها، وسنقوم بإخطارك وإطلاعك على أي تعديل في حينه.\n\nتعديل الخدمة\n\nيمكنك في أي وقت زيارة أقرب فرع لتعديل حسابك الأساسي، أو إعادة ترتيب حساباتك الأخرى التي ترغب في السحب منها لتغطية التزاماتك وفقًا لرغبتك.\n\nلن يتم تفعيل خاصية Sweeping على: -\n\nالحسابات المشتركة.\n\nالحسابات التي يديرها شخص آخر نيابة عنك (الواهب – الوصي - الولي الطبيعي – الولي الشرعي – القيم – الوكيل عن الغائب).\n\nالحسابات الإسلامية.\n\nالحسابات الجارية المدينة.\n\nالحسابات بالعملة الأجنبية.\n\nالحسابات الراكدة – حسابات المتوفيين\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات أخري\n\n#ProductOtherLayoutContainer#\n\nللمقارنة بين المنتجات اضغط...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "9d99ec743f0cac189083cc45ee10b1e268d4e1d6df81c56a868d4dff05b3f21f",
    "extracted_at": "2026-07-14T08:40:01.749879+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/a3bafbf63660d33a.json
{
  "id": "a3bafbf63660d33a",
  "title": "البنك الأهلى المصرى - خدمة الكشف الإلكتروني للحسابات",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22287%22%2C%22ProductID%22%3A%22%D8%AE%D8%AF%D9%85%D8%A9%20%D8%A7%D9%84%D9%83%D8%B4%D9%81%20%D8%A7%D9%84%D8%A5%D9%84%D9%83%D8%AA%D8%B1%D9%88%D9%86%D9%8A%20%D9%84%D9%84%D8%AD%D8%B3%D8%A7%D8%A8%D8%A7%D8%AA_18711%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nخدمات الحسابات\n\nخدمة الكشف الإلكتروني للحسابات\n\n#ProductHeaderContainer#\n\nتعريف الخدمة:\n\nخدمة إيقاف طباعة كشوف الحسابات الورقية والاطلاع على كشف الحساب الدوري من خلال الاهلي نت / الاهلي موبايل.\n\nكيفية الاشتراك في الخدمة.\n\nالدخول على الخدمة الذاتية والاشتراك في الخدمة باستخدام الرابط التالي\n\nالفروع الالكترونية\n\nزيارة أقرب فرع من فروع مصرفنا.\n\nمركز الاتصال الهاتفي رقم 19623\n\nمزايا الخدمة:\n\nسهولة طلب الخدمة\n\nالاطلاع علي كشف حساباتك المصرفية بالإضافة إلى بيان بالشهادات، والودائع لأجل، والقروض، وصناديق الاستثمار الخاصة بكم.\n\nسهولة الاطلاع علي كشف الحساب الدوري من خلال الأهلي نت / الأهلي موبايل دون الحاجة لانتظار كشف الحساب الورقي والاحتفاظ به\n\nيتيح البنك للعميل بنهاية العام المالي \"نموذج المصادقة\" على أرصدة حسابه/حساباته رفق الكشف الإلكتروني للحساب/للحسابات ليقوم العميل بمراجعتها والتوقيع علي نموذج المصادقة بالاعتماد أو استيفاء ملاحظاته (إن وجدت) بالنموذج وإرساله على العنوانين الموضحين به.\n\nالتمتع بالأمان عند الاطلاع على كشف الحساب الدوري من خلال خدمة الاهلي نت / الاهلي موبايل باستخدام اسم المستخدم والرقم السري الخاص بكم.\n\nللاطلاع على تعريفة أسعار الخدمة برجاء الضغط على الرابط التالي\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات أخري\n\n#ProductOtherLayoutContainer#\n\nللمقارنة بين المنتجات اضغط...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "1595f9da308c2ae99b2c41739e81516296fb5f45281de4f6b35c5d59d04d98a7",
    "extracted_at": "2026-07-14T08:40:01.357445+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/36bb2ed88dc65929.json
{
  "id": "36bb2ed88dc65929",
  "title": "البنك الأهلى المصرى - حساب التوفير",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22SavingLocalAccountsID%22%2C%22ProductID%22%3A%22%D8%AD%D8%B3%D8%A7%D8%A8%20%D8%A7%D9%84%D8%AA%D9%88%D9%81%D9%8A%D8%B1_6204%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالحسابات\n\nحسابات التوفير\n\nحسابات التوفير - عملة محلية\n\nحساب التوفير\n\n#ProductHeaderContainer#\n\nالخصائص\n\n5,000\n\nجم\n\n10,001\n\nمصري\n\nأجنبي\n\nقاصر (باسمه تحت الولاية أو الوصاية أو الهبه).\n\nسعر العائد\n\nالشهري يصل الى\n\n11.30 %\n\nالربع سنوي يصل الى\n\n11.35 %\n\nالنصف سنوي يصل الى\n\n11.40 %\n\nالسنوي يصل الى\n\n11.50 %\n\nالأوراق المطلوبة\n\nنسخة من بطاقة الهوية / جواز السفر\n\nشهادة الميلاد للقصر\n\nمميزات أخري\n\nمرونة فى صرف العائد.\n\nالخدمات المصرفية عبرالإنترنت\n\nحساب مشترك.\n\nبطاقة خصم مباشر للسحب والشراء.\n\nتمتع بالإعفاء من مصاريف فتح الحساب والحد الأدنى لفتح الحساب عند فتح حسابك من خلال الأهلي نت/الأهلي موبايل.\n\nشرائح الرصيد/دورية العائد\n\nشهري\n\nربع سنوي\n\nنص سنوي\n\nسنوي\n\nحتى 10,000 جم\n\n0%\n\nمن 10,001 الي 100,000جم\n\n7.50%\n\n7.55%\n\n7.60%\n\n7.70%\n\nمن 100,001 الي 500,000 جم\n\n7.75%\n\n7.85%\n\n7.90%\n\n8.00%\n\nمن 500,001 الى 2,000,000 جم\n\n8.50%\n\n8.60%\n\n8.75%\n\n9%\n\nمن 2,000,001 الى 5,000,000 جم\n\n9.30%\n\n9.35%\n\n9.40%\n\n9.50%\n\nمن 5,000,001 الى 10,000,000 جم\n\n10.30%\n\n10.35%\n\n10.40%\n\n10.50%\n\nمن 10,000,001 الى 20,000,000 جم\n\n10.80%\n\n10.85%\n\n10.90%\n\n11.00%\n\nأكثر من 20 مليون جم\n\n11.30%\n\n11.35%\n\n11.40%\n\n11.50%\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات أخري\n\nحساب توفير المدخر الصغير\n\nالحد الادني لفتح الحساب\n\n1000 جم\n\nحساب توفير المستقبل\n\nبدون حد ادني لفتح الحساب جم\n\nحساب توفير المعاش\n\n5000 جم\n\nحساب الأهلي اكسترا توفير\n\n20,000 جم\n\nللمقارنة بين المنتجات اضغط...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة\n\n| شرائح الرصيد/دورية العائد | شهري | ربع سنوي | نص سنوي | سنوي |\n| --- | --- | --- | --- | --- |\n| حتى 10,000 جم | 0% |  |  |  |\n| من 10,001 الي 100,000جم | 7.50% | 7.55% | 7.60% | 7.70% |\n| من 100,001 الي 500,000 جم | 7.75% | 7.85% | 7.90% | 8.00% |\n| من 500,001 الى 2,000,000 جم | 8.50% | 8.60% | 8.75% | 9% |\n| من 2,000,001 الى 5,000,000 جم | 9.30% | 9.35% | 9.40% | 9.50% |\n| من 5,000,001 الى 10,000,000 جم | 10.30% | 10.35% | 10.40% | 10.50% |\n| من 10,000,001 الى 20,000,000 جم | 10.80% | 10.85% | 10.90% | 11.00% |\n| أكثر من 20 مليون جم | 11.30% | 11.35% | 11.40% | 11.50% |",
  "metadata": {
    "content_hash": "0b4f53cd43127d1c0a7feb6d67ee37d169a9a757219e0eb2d53f99268decd95a",
    "extracted_at": "2026-07-14T08:39:43.498742+00:00",
    "has_tables": true,
    "source": "playwright_rescrape",
    "error": null
  }
}
