=== DigiGradProject/SmartBankSearch/nbe-ai-search-mvp/data/schemas/document.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "NBE Document",
  "type": "object",
  "required": ["id", "title", "url", "language", "content"],
  "properties": {
    "id": { "type": "string" },
    "title": { "type": "string" },
    "url": { "type": "string", "format": "uri" },
    "language": { "enum": ["ar", "en"] },
    "content": { "type": "string", "minLength": 1 },
    "metadata": { "type": "object" }
  }
}

=== DigiGradProject/SmartBankSearch/output/793ecbc22b51a2c3.json
{
  "id": "793ecbc22b51a2c3",
  "title": "البنك الأهلى المصرى - حسابات التوفير",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductCategory?inParams=%7B%22CategoryID%22%3A%22Saving%20Accounts%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالحسابات\n\nحسابات التوفير\n\nCatagory landing div\n\nحسابات التوفير - عملة محلية\n\nسهولة السحب و الايداع و التمتع بعائد دوري علي مدخراتك\n\nحسابات التوفير- عملة أجنبية\n\nسهولة السحب والايداع مع العائد وإمكانية فتح الحساب بالدولار الأمريكي ، الجنيه الإسترليني ، اليورو\n\n#CategoryMiddleContainer#\n\n#ProductShortLayoutContainer#\n\nاظغط للمقارنة بين المنتجات.\n\n#CategoryFooterContainer#\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "8c6eaeec9f2f664e641316f1089f268edf9b9303b57e627e40a1b9d923cba25b",
    "extracted_at": "2026-07-14T08:39:39.841924+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/59cc5bb80678f31d.json
{
  "id": "59cc5bb80678f31d",
  "title": "البنك الأهلى المصرى - وورلد إيليت",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22DepitCardsID%22%2C%22ProductID%22%3A%22%D9%88%D9%88%D8%B1%D9%84%D8%AF%20%D8%A5%D9%8A%D9%84%D9%8A%D8%AA_18689%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالبطاقات\n\nبطاقات الخصم المباشر\n\nوورلد إيليت\n\n#ProductHeaderContainer#\n\nمميزات البطاقة\n\n5 سنوات\n\nمحليا\n\nمتاح\n\nالبطاقة مصممة لعملاء البنك من الأفراد الطبيعيين،  ذوي الملاءة المالية التي تبلغ أرصدتهم أكثر من 20 مليون جنيه مصري (أو ما يعادلها بالعملات الأجنبية)\n\nالإدراج التلقائي ببرنامج Al Ahly Points  الذي يتيح لكم الحصول على (1.50 نقطة) على كل جنيه مصري يتم استخدامه في المشتريات.\n\nاستبدل نقاطك من خلال\n\n#ProductTypeMiddleContainer#\n\nمميزات \nبطاقات الخصم المباشر\n\nالمرونة\n\nاستخدام البطاقة محليا في المشتريات والسحب النقدى.\n\nالامان\n\nالتسوق الامن عبر الأنترنت من خلال خدمة الكود الامن للشراء (OTP)\n\n24/7 الأهلي فون\n\nنتشرف بخدمتكم واجابة جميع استفساراتكم من خلال خدمة\nالأهلي فون 19523 محليا و 0020225941200 دوليا\n\n#CategoryFooterContainer#\n\nOthers Products\n\n#ProductOtherLayoutContainer#\n\nTo compare between products press...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "6171ed0f1fc4aa833345a1b04ac5bb7d72d57dcc93fb02947c66711fe7f42d66",
    "extracted_at": "2026-07-14T08:40:46.191823+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/c09c14c04b7fe90c.json
{
  "id": "c09c14c04b7fe90c",
  "title": "البنك الأهلى المصرى - شهادة استثمار ' ب '",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22InvestmentCertificateCatID%22%2C%22ProductID%22%3A%22%D8%B4%D9%87%D8%A7%D8%AF%D8%A9%20%D8%A7%D8%B3%D8%AA%D8%AB%D9%85%D8%A7%D8%B1%20'%20%D8%A8%20'_6348%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nشهادات الادخار\n\nشهادات الاستثمار\n\nشهادة استثمار ' ب '\n\n#ProductHeaderContainer#\n\nفئات الشهادة\n\n500\n\nجم\n\nومضاعفاتها\n\nالمدة\n\nسنة\n\nدورية صرف العائد\n\nشهري\n\nسعر العائد\n\n14%\n\nمن يحق لهم الشراء\n\nتصدر الشهادات للأشخاص الطبيعيين المصريين والأجانب بالغين و قصر\n\nالاقتراض\n\nيجوز الاقتراض بضمان هذه الشهادات من أي من فروع مصرفنا وفقاً والتعليمات السارية و اسعار العوائد في تاريخ الاقتراض\n\nألاسترداد\n\nتسترد الشهادة في نهاية المدة بكامل قيمتها الاسمية , ويمكن استردادها بعد مضي ستة اشهر من يوم العمل التالي ليوم الشراء وفقا و القيم الاستردادية المعدة في هذا الشان.\n\nمميزات أخري\n\nيتم صرف العائد من خلال ماكينات الصرف الالى المنتشرة في جميع أنحاء الجمهورية خلال أيام الأسبوع وعلى مدار 24 ساعة\n\nمدة الشهادة سنة واحدة تبدأ من يوم العمل التالي لتاريخ الشراء و تجدد تلقائيا في تاريخ أستحقاقها ما لم يتم أستردادها أو وجود تعليمات بخلاف ذلك.\n\nتدر الشهادات عائد دوري شهري بسعر عائد ثابت طوال مدة الشهادة يحدد وفقا للسعر السائد في تاريخ اصدار الشهادات  و يحتسب اعتبارا من يوم العمل التالي لتاريخ الشراء, و يصرف في تاريخ استحقاقه.\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات اخرى\n\nشهادة استثمار ' أ '\n\n10\n\nشهادة استثمار 'ج '\n\n20\n\nللمقارنة بين المنتجات إضغط ...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "baf9f014f0dadc43181931276506f7ebf81eaa65a16b6d04c5f79f8b78538859",
    "extracted_at": "2026-07-14T08:39:25.369295+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/a60ce530d4ae3d07.json
{
  "id": "a60ce530d4ae3d07",
  "title": "البنك الأهلى المصرى - حساب توفير المستقبل",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22OpenYourBankAccountInEgypt%22%2C%22ProductID%22%3A%22%D8%AD%D8%B3%D8%A7%D8%A8%20%D8%AA%D9%88%D9%81%D9%8A%D8%B1%20%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D9%82%D8%A8%D9%84_6353%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالحسابات\n\nمبادرة افتح حسابك في مصر\n\nحساب توفير المستقبل\n\n#ProductHeaderContainer#\n\nالخصائص\n\nبدون حد ادني لفتح الحساب\n\n3001\n\nسعر العائد\n\nالشهري يصل الى\n\n7.50 %\n\nالربع سنوي يصل الى\n\n7.60 %\n\nالنصف سنوي يصل الى\n\n7.65 %\n\nالسنوي يصل الى\n\n7.75 %\n\nالأوراق المطلوبة\n\nنسخة من بطاقة الهوية / جواز السفر وبأبسط الإجراءات\n\nمميزات أخري\n\nالحد الأقصى لرصيد الحساب: 1 مليون جنيها مصريًا\n\nالحد الأقصى لحركات الخصم اليومي (سحب نقدي – حوالات صادرة – خصم حسابي ... إلخ) 90 ألف جنيهًا مصريًا\n\nالحد الأقصى لحركات الخصم الشهري ( سحب نقدي – حوالات صادرة – خصم حسابي ... إلخ) 300 الف جنيهًا مصريًا\n\nتامين  مجاني علي الحياه للعميل\n\nيستحق  التامين اعتبارا من الشهر التالي لتاريخ فتح الحساب علي اقل رصيد دائن بالحساب خلال الشهر بحد ادني مبلغ 5000 جم و بحد اقصي للتامين مبلغ 100 الف جم\n\nيتم دفع مبلغ التامين وفقا واقل رصيد دائن للشهر السابق لتاريخ الوفاه.\n\nالتامين سارى للعملاء من سن 15 وحتى 60 سنه.\n\nبشرط الا يقل سن العميل عن 15 سنه ولا يزيد عن 50 سنه عند بدء التأمين.\n\nاصدار محفظة فون كاش معفاة من (مصاريف الاصدار- مصاريف سنوية لمده سنه من تاريخ الاشتراك بالمحفظة).\n\nإمكانية شراء شهادات الاستثمار ( أ-ب-ج) خصما من الحساب وإضافة قيمة الشهادة و العائد عليه.\n\nيتم احتساب العائد شهريا علي اقل رصيد دائن خلال الشهر و الذي يزيد عن 3000 جنيه و يتم تعليه العائد المحتسب علي رصيد الحساب وفقا و دوريه صرفه\n\nمصاريف فتح الحساب: مجانا\n\nالمصاريف الإدارية: مجانا\n\nمصاريف اصدار بطاقة الخصم المباشر: مجانا\n\nالخدمات المصرفية عبرالإنترنت\n\nبطاقة خصم مباشر للسحب والشراء.\n\nكشف الحساب الالكتروني من خلال الأهلي نت / الأهلي موبايل : مجانا\n\nشرائح الرصيد/دورية العائد\n\nشهري\n\nربع سنوي\n\nنص سنوي\n\nسنوي\n\nحتى 3000 جم\n\n0%\n\nمن 3001 : 100,000 جم\n\n7.25%\n\n7.30%\n\n7.35%\n\n7.45%\n\nمن 100,001 : 1 مليون جم\n\n7.50%\n\n7.60%\n\n7.65%\n\n7.75%\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات أخري\n\nحساب توفير المدخر الصغير\n\nالحد الادني لفتح الحساب\n\n1000 جم\n\nحساب توفير المعاش\n\n5000 جم\n\nحساب التوفير\n\n5,000 جم\n\nحساب الأهلي اكسترا توفير\n\n20,000 جم\n\nللمقارنة بين المنتجات اضغط...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة\n\n| شرائح الرصيد/دورية العائد | شهري | ربع سنوي | نص سنوي | سنوي |\n| --- | --- | --- | --- | --- |\n| حتى 3000 جم | 0% |  |  |  |\n| من 3001 : 100,000 جم | 7.25% | 7.30% | 7.35% | 7.45% |\n| من 100,001 : 1 مليون جم | 7.50% | 7.60% | 7.65% | 7.75% |",
  "metadata": {
    "content_hash": "de4bdb47252c89c57cfbe9583040a4b3b79f54f4234171067dc0317baaa1db2c",
    "extracted_at": "2026-07-14T08:39:57.701080+00:00",
    "has_tables": true,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/0d7852c6a0e76d6f.json
{
  "id": "0d7852c6a0e76d6f",
  "title": "البنك الأهلى المصرى - بطاقة ميزة المدفوعة مقدما",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22PrepaidCardsID%22%2C%22ProductID%22%3A%22%D8%A8%D8%B7%D8%A7%D9%82%D8%A9%20%D9%85%D9%8A%D8%B2%D8%A9%20%D8%A7%D9%84%D9%85%D8%AF%D9%81%D9%88%D8%B9%D8%A9%20%D9%85%D9%82%D8%AF%D9%85%D8%A7_16535%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالبطاقات\n\nالبطاقات المدفوعة مقدما\n\nبطاقة ميزة المدفوعة مقدما\n\n#ProductHeaderContainer#\n\nهي اول بطاقة دفع الكتروني وطنية و التي تعد احد الادوات الرئيسية للسداد الالكتروني لمدفوعات المواطن سواء للجهات الحكومية او في كافة التعاملات المالية الاخرى محليا.\n\nخصائص البطاقة\n\nتمكنك من استقبال و صرف الحوالات بالجنية المصري على مدار 24 ساعة دون الحاجة للتوجه لأي من فروع البنك .\n\nالاستفادة من المعاملات اللاتلامسية للحفاظ علي سلامتك\n  .\n\nتمنحك إمكانية الاستمتاع بخدمة الإنترنت البنكي.\n\nتمنحك إمكانية الاستمتاع بخدمات محفظة الهاتف المحمول لدفع فواتيرك وشحن رصيد موبايلك وغيرهم من الخدمات.\n\nتعد بطاقة ميزة المدفوعة مقدما من البنك الاهلي المصري اول بطاقة دفع الكترونية وطنية تمكنك من سداد المدفوعات الحكومية الكترونيا بسهولة و امان\n\nتوفر بطاقة ميزة حرية السحب النقدي من خلال شبكة الصراف الالي الخاصة بالبنك الاهلي المصري او من خلال ماكينات البنوك الأخرى داخل مصر التي تحمل علامة 123 .\n\nوجود شعار ميزة يتيح لك قبول البطاقة لدى شبكة واسعة من التجار المتاح لديهم نقاط البيع الالكترونية و التي تمكنك من شراء السلع و الحصول على الخدمات من خلال البطاقة.\n\nصورة البطاقة الشخصية السارية او جواز السفر الموضح به الرقم القومي.\n\nيرجى زيارة اقرب فرع من فروع مصرفنا\n\nللاطلاع علي الشروط و الأحكام\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nTo compare between products press...\n\n#ProductTypeFooterContainer#\n\nبطاقة ميزة المدفوعة مقدما من البنك الأهلي المصري\n\nس : ما هي بطاقة ميزة المدفوعة مقدما من البنك الأهلي المصري ؟\n\nس : ما هي اجراءات الحصول على هذه البطاقات ؟\n\nالتوجه الى اقرب فرع من فروع البنك الأهلي المصري المنتشرة داخل جمهورية مصر العربية.\n\nاستيفاء طلب الاصدار الخاص ببطاقة ميزة المدفوعة مقدما و ارفاقه مع صورة بطاقة الرقم القومي السارية او جواز سفر ساري موضح به الرقم القومي.\n\nاستلام بطاقة الدفع و انتظار الرسالة النصية الخاصة بتفعيل تلك البطاقة.\n\n\"يتم استلام البطاقة في الحال بدون اسم مطبوع عليها, و في حال طلبكم لبطاقة مطبوع عليها يتم تقديم الطلب و استلام البطاقة خلال مدة يتم افادتكم بها\"\n\nس : هل بمجرد استلام البطاقة يمكن استخدامها ؟\n\nس : و كيف احصل على الرقم السري الخاص بالبطاقة ؟\n\nالبند\n\nبطاقة ميزة\n\nمصاريف الاصدار\n\n30 جم\n\nالمصاريف السنوية\n\n20 جم\n\nمصاريف اصدار بدل فاقد / تالف\n\nعمولة الايداع من خلال ATM / فروع مصرفنا\n\nمجانا\n\nعمولة السحب النقدي من خلال ال ATM الخاصة بمصرفنا\n\nعمولة السحب النقدي من خلال ال ATM الخاصة بالبنوك المحلية\n\n5  جم\n\nعمولة الشراء من المتاجر\n\nالحد الاقصى لرصيد البطاقة\n\n200,000 جم\n\nالحد الاقصى للشراء اليومي / محليا\n\n30,000 جم\n\nالحد الاقصى للسحب النقدي اليومي / محليا\n\nالحد الاقصى للاستخدام اليومي / محليا\n\n60,000 جم\n\nالحد الاقصي للتعامل شهريا بالبطاقة\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة\n\n| البندبطاقة ميزةمصاريف الاصدار30 جمالمصاريف السنوية20 جممصاريف اصدار بدل فاقد / تالف30 جمعمولة الايداع من خلال ATM / فروع مصرفنامجاناعمولة السحب النقدي من خلال ال ATM الخاصة بمصرفنامجاناعمولة السحب النقدي من خلال ال ATM الخاصة بالبنوك المحلية5  جمعمولة الشراء من المتاجرمجاناالحد الاقصى لرصيد البطاقة200,000 جمالحد الاقصى للشراء اليومي / محليا30,000 جمالحد الاقصى للسحب النقدي اليومي / محليا30,000 جمالحد الاقصى للاستخدام اليومي / محليا60,000 جمالحد الاقصي للتعامل شهريا بالبطاقة200,000 جم | البند | بطاقة ميزة | مصاريف الاصدار | 30 جم | المصاريف السنوية | 20 جم | مصاريف اصدار بدل فاقد / تالف | 30 جم | عمولة الايداع من خلال ATM / فروع مصرفنا | مجانا | عمولة السحب النقدي من خلال ال ATM الخاصة بمصرفنا | مجانا | عمولة السحب النقدي من خلال ال ATM الخاصة بالبنوك المحلية | 5  جم | عمولة الشراء من المتاجر | مجانا | الحد الاقصى لرصيد البطاقة | 200,000 جم | الحد الاقصى للشراء اليومي / محليا | 30,000 جم | الحد الاقصى للسحب النقدي اليومي / محليا | 30,000 جم | الحد الاقصى للاستخدام اليومي / محليا | 60,000 جم | الحد الاقصي للتعامل شهريا بالبطاقة | 200,000 جم |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| البند | بطاقة ميزة |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| مصاريف الاصدار | 30 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| المصاريف السنوية | 20 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| مصاريف اصدار بدل فاقد / تالف | 30 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| عمولة الايداع من خلال ATM / فروع مصرفنا | مجانا |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| عمولة السحب النقدي من خلال ال ATM الخاصة بمصرفنا | مجانا |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| عمولة السحب النقدي من خلال ال ATM الخاصة بالبنوك المحلية | 5  جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| عمولة الشراء من المتاجر | مجانا |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| الحد الاقصى لرصيد البطاقة | 200,000 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| الحد الاقصى للشراء اليومي / محليا | 30,000 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| الحد الاقصى للسحب النقدي اليومي / محليا | 30,000 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| الحد الاقصى للاستخدام اليومي / محليا | 60,000 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n| الحد الاقصي للتعامل شهريا بالبطاقة | 200,000 جم |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |\n\n| البند | بطاقة ميزة |\n| --- | --- |\n| مصاريف الاصدار | 30 جم |\n| المصاريف السنوية | 20 جم |\n| مصاريف اصدار بدل فاقد / تالف | 30 جم |\n| عمولة الايداع من خلال ATM / فروع مصرفنا | مجانا |\n| عمولة السحب النقدي من خلال ال ATM الخاصة بمصرفنا | مجانا |\n| عمولة السحب النقدي من خلال ال ATM الخاصة بالبنوك المحلية | 5  جم |\n| عمولة الشراء من المتاجر | مجانا |\n| الحد الاقصى لرصيد البطاقة | 200,000 جم |\n| الحد الاقصى للشراء اليومي / محليا | 30,000 جم |\n| الحد الاقصى للسحب النقدي اليومي / محليا | 30,000 جم |\n| الحد الاقصى للاستخدام اليومي / محليا | 60,000 جم |\n| الحد الاقصي للتعامل شهريا بالبطاقة | 200,000 جم |",
  "metadata": {
    "content_hash": "907764acba980bef1b39143daa312a8c26afe512b407b1b0d82bada0057f0fd8",
    "extracted_at": "2026-07-14T08:40:50.209412+00:00",
    "has_tables": true,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/6fafc3565d7a40f1.json
{
  "id": "6fafc3565d7a40f1",
  "title": "البنك الأهلى المصرى - حساب توفير المستقبل",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22SavingForeignAccountsID%22%2C%22ProductID%22%3A%22%D8%AD%D8%B3%D8%A7%D8%A8%20%D8%AA%D9%88%D9%81%D9%8A%D8%B1%20%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D9%82%D8%A8%D9%84_19862%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nالحسابات\n\nحسابات التوفير\n\nحسابات التوفير- عملة أجنبية\n\nحساب توفير المستقبل\n\n#ProductHeaderContainer#\n\nالخصائص\n\nبدون حد ادني لفتح الحساب\n\n100 دولار أمريكي - يورو - جنيه إسترليني\n\nالعملاء من سن 15 سنة و بدون حد اقصي\n\nسعر العائد\n\nالشهري يصل الى\n\n1.50 % سنويًا\n\nالسنوي يصل الى\n\n2.00 % سنويًا\n\nالأوراق المطلوبة\n\nبطاقة الهوية / جواز السفر\n\nمميزات أخري\n\nالحد الأقصى لرصيد الحساب: 20 ألف دولار أمريكي - يورو - جنيه إسترليني.\n\nالحد الأقصى لحركات الخصم اليومي (سحب نقدي – حوالات صادرة – خصم حسابي ... إلخ) ما يعادل 90 ألف جنيه مصري.\n\nالحد الأقصى لحركات الخصم الشهري (سحب نقدي – حوالات صادرة – خصم حسابي ... إلخ) ما يعادل 300 ألف جنيه مصري.\n\nغير متاح إصدار بطاقة خصم مباشر.\n\nإمكانية شراء الشهادات / الودائع بالعملة الأجنبية وإضافة العائد على الحساب.\n\nمصاريف فتح الحساب: مجانًا.\n\nالمصاريف الإدارية (طبقا لعملة الحساب): 1 (دولار أمريكي, يورو, جنيه إسترليني) تخصم كل 3 شهور.\n\nكشف الحساب الورقي: ما يعادل 100 جم للكشف يخصم كل 3 شهور.\n\nكشف الحساب الإلكتروني من خلال الأهلي نت / الأهلي موبايل: مجانًا.\n\n(جوائز دورية من خلال الدخول في سحب ربع سنوي بالمحددات التالية (لعملة الدولار الأمريكي فقط:\n\nلكل 100 دولار أمريكي يحتفظ بها العميل بالحساب كل 3 أشهر فرصة للفوز ودخول السحب.\n\nقيمه الجائزة: 50 ألف جم يتم إضافتها على بطاقة مسبقة الدفع (ميزة) أو حساب العميل بالعملة المحلية إن وجد.\n\nعدد 2 عملاء الفائزين ربع سنويًا.\n\nموعد إجراء السحب: خلال أشهر (يناير، إبريل، يوليو، أكتوبر).\n\nيحصل العميل الفائز على صافي مبلغ الجائزة بعد استقطاع نسبة  30%الخاصة بمصلحة الضرائب ووزارة التضامن الاجتماعي تطبيقًا للشروط والأحكام.\n\nيتم استبعاد العملاء الفائزين في السحوبات السابقة.\n\nشرائح الرصيد/دورية العائد\n\nدولار أمريكي\n\nيورو\n\nجنيه إسترليني\n\nيصرف شهري\n\nيصرف سنوي\n\nمن 100 وحتى 5,000 (دولار أمريكي - يورو  - جنيه إسترليني)\n\n1.00% سنويًا\n\n1.25% سنويًا\n\n0.50%\nسنويًا\n\n0.75%\nسنويًا\n\n1.00%\nسنويًا\n\nمن 5,001 وحتى 20,000 (دولار أمريكي - يورو - جنيه إسترليني)\n\n1.50% سنويًا\n\n2.00%\nسنويًا\n\n1.25%\nسنويًا\n\n1.50%\nسنويًا\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات أخري\n\nحساب التوفير\n\nالحد الادني لفتح الحساب وإحتساب العائد\n\n100\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة\n\n| شرائح الرصيد/دورية العائد | دولار أمريكي | يورو | جنيه إسترليني |\n| --- | --- | --- | --- |\n| يصرف شهري | يصرف سنوي | يصرف شهري | يصرف سنوي |\n| من 100 وحتى 5,000 (دولار أمريكي - يورو  - جنيه إسترليني) | 1.00% سنويًا | 1.25% سنويًا | 0.50%\nسنويًا |\n| من 5,001 وحتى 20,000 (دولار أمريكي - يورو - جنيه إسترليني) | 1.50% سنويًا | 2.00%\nسنويًا | 1.00% سنويًا |",
  "metadata": {
    "content_hash": "16474c7a444a799d62b96c5681ecdd56620b526539a423cd744e0b04a5b80a4f",
    "extracted_at": "2026-07-14T08:39:52.823825+00:00",
    "has_tables": true,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/f4faca5a5030f81d.json
{
  "id": "f4faca5a5030f81d",
  "title": "البنك الأهلى المصرى - شهادة استثمار ' أ '",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22InvestmentCertificateCatID%22%2C%22ProductID%22%3A%22%D8%B4%D9%87%D8%A7%D8%AF%D8%A9%20%D8%A7%D8%B3%D8%AA%D8%AB%D9%85%D8%A7%D8%B1%20'%20%D8%A3%20'_6349%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nشهادات الادخار\n\nشهادات الاستثمار\n\nشهادة استثمار ' أ '\n\n#ProductHeaderContainer#\n\nفئات الشهادة\n\n500\n\nجم\n\nومضاعفاتها\n\nالمدة\n\nسنوات\n\n10\n\nدورية صرف العائد\n\nفوائد تراكمية\n\nسعر العائد\n\n12%\n\nمن يحق لهم الشراء\n\nتصدر الشهادات للأشخاص الطبيعيين المصريين والأجانب بالغين و قصر\n\nالاقتراض\n\nيجوز الاقتراض بضمان هذه الشهادات من أي من فروع مصرفنا وفقاً والتعليمات السارية و اسعار العوائد في تاريخ الاقتراض\n\nألاسترداد\n\nتسترد الشهادة في نهاية مدتها بكامل قيمتها الاستحقاقية, و يمكن أستردادها بعد مضي ستة أشهر من يوم العمل التالي ليوم الشراء وفقا و القيم الاستردادية المعدة في هذا الشأن.\n\nمميزات أخري\n\nالعائد مجمع يمنح في نهاية مدة الشهادة\n\nتدر الشهادات عائد تراكمي بسعر عائد ثابت طوال مدة الشهادة يحدد وفقا للسعر السائد في تاريخ اصدار الشهادات و يحتسب اعتبارا من يوم العمل التالي لتاريخ الشراء\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات اخرى\n\nشهادة استثمار ' ب '\n\nشهادة استثمار 'ج '\n\n20\n\nللمقارنة بين المنتجات إضغط ...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "c5074dee596848a707c45f165b936fea334b3c282b8829388480dd19d9c8cf27",
    "extracted_at": "2026-07-14T08:39:23.011599+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}

=== DigiGradProject/SmartBankSearch/output/0f91703c57c78c61.json
{
  "id": "0f91703c57c78c61",
  "title": "البنك الأهلى المصرى - الذهبية الجديدة",
  "url": "https://www.nbe.com.eg/NBE/E/#/AR/ProductDetails?inParams=%7B%22CategoryID%22%3A%22ForigenCertificatesID%22%2C%22ProductID%22%3A%22%D8%A7%D9%84%D8%B0%D9%87%D8%A8%D9%8A%D8%A9%20%D8%A7%D9%84%D8%AC%D8%AF%D9%8A%D8%AF%D8%A9_16552%22%7D",
  "language": "ar",
  "content": "أفراد\n\nالشركات\n\nالمشروعات الصغيرة\n\nبلاتينم\n\nNab Bar Menu\n\nChange Language\n\nالوظائف\n\nSearch Bar\n\nNBE logo\n\nMega Menu\n\nشهادات الادخار\n\nشهادات الادخار بالعملات الاجنبية\n\nالذهبية الجديدة\n\n#ProductHeaderContainer#\n\n500\n\nدولار أمريكي / يورو\n\nومضاعفاتها\n\nسنوات\n\nدولار - 3 سنوات\n\nدولار - 5 سنوات\n\nدولار - 7 سنوات\n\nيورو (3 سنوات وعائد ربع سنوي فقط)\n\nالاقتراض\n\nيمكن الاقتراض بضمان هذه الشهادات من أي من فروع مصرفنا وفقاً والتعليمات السارية.\n\nالاسترداد\n\nلا يمكن الاسترداد قبل مضي 6 اشهر.\n\nيمكن استردادها قبل نهاية المدة وفقا والقواعد والشروط المعلنة في البنك.\n\nمميزات اخرى\n\nنوع العائد\n\nثابت طول مدة الشهادة.\n\nيحسب من يوم العمل التالي ليوم الشراء و يستحق بنفس عملة الشهادة.\n\n#ProductTypeMiddleContainer#\n\n#ProductMiddleContainer#\n\nمنتجات أخري\n\n#ProductOtherLayoutContainer#\n\nللمقارنة بين المنتجات إضغط ...\n\n#ProductTypeFooterContainer#\n\n#ProductFooterContainer#\n\nهذه الصفحه غير متاحة\n\nSiteMap\n\n1187 كورنيش النيل ، برج البنك الأهلي ، بولاق ، القاهرة ، مصر\n\nمحليا: 19623 - دوليا: 0020219623 / 0020225941200\n\nاتصل بنا على الفور على الخط الساخن على مدار 24-ساعة 19623 للإبلاغ عن مشكلة أو بطاقة مفقودة\n\nCopyrights\n\nFloating Banner\n\nهذه الرسالة تحتوي على بيانات شخصية أو مالية. لذلك, لن يتم تنفيذ طلبك.\n\nبرجاء عدم الإفصاح عن بياناتك الشخصية أو المالية أثناء استخدام الخدمة.\n\nThis message contains personal or financial information.\n\nTherefore, your request cannot be processes here.\n\nPlease do not disclose your personal or financial data when using this service.\n\nConfirm\n\nبرجاء العلم أن الخدمة للاستعلام فقط عن المنتجات والخدمات المقدمة من البنك للعملاء الأفراد والشركات.\n\nمرحبا، 👋\n\nدعنا نتحدث إذا كان لديك أي أسئلة",
  "metadata": {
    "content_hash": "0bd84270b6102bb7fe11420852a3dc70734c9f18797f7e587d112140f5de9589",
    "extracted_at": "2026-07-14T08:39:19.332254+00:00",
    "has_tables": false,
    "source": "playwright_rescrape",
    "error": null
  }
}
